# Generated by Django 2.1.4 on 2019-01-10 15:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMarker',
            fields=[
                ('hmarker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('date_float', models.FloatField(null=True)),
                ('date_string', models.CharField(max_length=256, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
