# Generated by Django 2.1.4 on 2019-01-16 21:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historymarker',
            name='description',
        ),
        migrations.AddField(
            model_name='historymarker',
            name='main_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historymarker',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=512), null=True, size=None),
        ),
    ]
