# Generated by Django 2.1.4 on 2019-01-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190116_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historymarker',
            name='date_float',
        ),
        migrations.AddField(
            model_name='historymarker',
            name='date_int',
            field=models.IntegerField(null=True),
        ),
    ]
