# Generated by Django 2.1.5 on 2019-01-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190116_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historymarker',
            old_name='date_int',
            new_name='year_int',
        ),
        migrations.RenameField(
            model_name='historymarker',
            old_name='date_string',
            new_name='year_string',
        ),
    ]
