# Generated by Django 2.1.3 on 2019-01-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curryworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymarker',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historymarker',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
