# Generated by Django 2.1.3 on 2019-01-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currymap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historymarker',
            name='date',
        ),
        migrations.AddField(
            model_name='historymarker',
            name='date_float',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historymarker',
            name='date_string',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
