# Generated by Django 2.1.3 on 2019-01-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currymap', '0002_auto_20190103_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymarker',
            name='date_string',
            field=models.CharField(max_length=256),
        ),
    ]
